training:
  batch_size: 128
  alpha: 0.15
  loss: huber
  num_episodes: 10000
  train_steps: 1000000
  warmup_episode: 10
  save_freq: 1000

optimizer:
  name: adam
  lr_min: 0.0001
  lr_decay: 5000

rl:
  gamma: 0.60
  max_steps_per_episode: 200
  target_model_update_episodes: 20
  max_queue_length: 50000

epsilon:
  max_epsilon: 1
  min_epsilon: 0.01
  decay_epsilon: 0.001
  